const TOTAL_COINS = Number(329.5 * 1000000);

const TRANSACTION_THRESHOLD = 5;

const FIRST_LEADER = '';

const TRANSACTION_FEE = 5;

const VALIDATOR_FEE = 25;

const TIER_TWO_BLOCK_REQUIREMENT = 10;
const TIER_ONE_BLOCK_REQUIREMENT = 20;

module.exports = {
  TOTAL_COINS,
  TRANSACTION_THRESHOLD,
  FIRST_LEADER,
  TRANSACTION_FEE,
  VALIDATOR_FEE,
  TIER_TWO_BLOCK_REQUIREMENT,
  TIER_ONE_BLOCK_REQUIREMENT,
};
